# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\WidgetApoyo\InterfazBusquedaProductos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(663, 431)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Fondo_buscar_productos = QtWidgets.QWidget(Form)
        self.Fondo_buscar_productos.setStyleSheet("#Fondo_buscar_productos{\n"
"    background-color: #397bb8;\n"
"}")
        self.Fondo_buscar_productos.setObjectName("Fondo_buscar_productos")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Fondo_buscar_productos)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contenedor_busqueda_productos = QtWidgets.QWidget(self.Fondo_buscar_productos)
        self.contenedor_busqueda_productos.setStyleSheet("#contenedor_busqueda_productos{\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}")
        self.contenedor_busqueda_productos.setObjectName("contenedor_busqueda_productos")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.contenedor_busqueda_productos)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_busqueda_productos = QtWidgets.QScrollArea(self.contenedor_busqueda_productos)
        self.scrollArea_busqueda_productos.setWidgetResizable(True)
        self.scrollArea_busqueda_productos.setObjectName("scrollArea_busqueda_productos")
        self.scrollAreaWidgetContents_busqueda_productos = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_busqueda_productos.setGeometry(QtCore.QRect(0, 0, 631, 336))
        self.scrollAreaWidgetContents_busqueda_productos.setStyleSheet("#scrollAreaWidgetContents_busqueda_productos{\n"
"    background-color: white;\n"
"}")
        self.scrollAreaWidgetContents_busqueda_productos.setObjectName("scrollAreaWidgetContents_busqueda_productos")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_busqueda_productos)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_busqueda_productos.setWidget(self.scrollAreaWidgetContents_busqueda_productos)
        self.verticalLayout_3.addWidget(self.scrollArea_busqueda_productos)
        self.verticalLayout_2.addWidget(self.contenedor_busqueda_productos)
        self.horizontalWidget_botones_busqueda = QtWidgets.QWidget(self.Fondo_buscar_productos)
        self.horizontalWidget_botones_busqueda.setStyleSheet("#horizontalWidget_botones_busqueda QPushButton{\n"
"    background-color: #e73a4b;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"    padding: 6px 9px;\n"
"    border: none;\n"
"}\n"
"\n"
"#horizontalWidget_botones_busqueda QPushButton::hover{\n"
"    background-color: #EC5B69\n"
"}")
        self.horizontalWidget_botones_busqueda.setObjectName("horizontalWidget_botones_busqueda")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget_botones_busqueda)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_agregar_productos_busqueda = QtWidgets.QPushButton(self.horizontalWidget_botones_busqueda)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_agregar_productos_busqueda.setFont(font)
        self.pushButton_agregar_productos_busqueda.setStyleSheet("#pushButton_agregar_productos_busqueda{\n"
"    background-color: #e73a4b;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border-radius: 4px;\n"
"    padding: 6px 9px;\n"
"    border: none;\n"
"}\n"
"\n"
"#pushButton_agregar_productos_busqueda::hover{\n"
"    background-color: #EC5B69\n"
"}")
        self.pushButton_agregar_productos_busqueda.setObjectName("pushButton_agregar_productos_busqueda")
        self.horizontalLayout.addWidget(self.pushButton_agregar_productos_busqueda)
        self.pushButton = QtWidgets.QPushButton(self.horizontalWidget_botones_busqueda)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.horizontalWidget_botones_busqueda)
        self.verticalLayout.addWidget(self.Fondo_buscar_productos)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_agregar_productos_busqueda.setText(_translate("Form", "Agregar Productos"))
        self.pushButton.setText(_translate("Form", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
