# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\WidgetApoyo\LoadingScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(411, 123)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(411, 123))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.background_loadingScreen = QtWidgets.QWidget(Form)
        self.background_loadingScreen.setObjectName("background_loadingScreen")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.background_loadingScreen)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gif_loadingScreen = QtWidgets.QLabel(self.background_loadingScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gif_loadingScreen.sizePolicy().hasHeightForWidth())
        self.gif_loadingScreen.setSizePolicy(sizePolicy)
        self.gif_loadingScreen.setMinimumSize(QtCore.QSize(75, 75))
        self.gif_loadingScreen.setMaximumSize(QtCore.QSize(75, 75))
        self.gif_loadingScreen.setScaledContents(True)
        self.gif_loadingScreen.setWordWrap(True)
        self.gif_loadingScreen.setObjectName("gif_loadingScreen")
        self.verticalLayout_2.addWidget(self.gif_loadingScreen, 0, QtCore.Qt.AlignHCenter)
        self.text_loadingScreen = QtWidgets.QLabel(self.background_loadingScreen)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_loadingScreen.setFont(font)
        self.text_loadingScreen.setObjectName("text_loadingScreen")
        self.verticalLayout_2.addWidget(self.text_loadingScreen, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.background_loadingScreen)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.gif_loadingScreen.setText(_translate("Form", "TextLabel"))
        self.text_loadingScreen.setText(_translate("Form", "Cargando..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
