# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\WidgetApoyo\NoImageFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(264, 61)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.background = QtWidgets.QWidget(Form)
        self.background.setStyleSheet("#background{\n"
"    background-color: #397bb8;\n"
"    border-radius: 20px;\n"
"}")
        self.background.setObjectName("background")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.background)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.background)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.punto = QtWidgets.QLabel(self.frame)
        self.punto.setMaximumSize(QtCore.QSize(14, 14))
        self.punto.setScaledContents(True)
        self.punto.setObjectName("punto")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.punto)
        self.nombre = QtWidgets.QLabel(self.frame)
        self.nombre.setObjectName("nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nombre)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.background)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.punto.setText(_translate("Form", "TextLabel"))
        self.nombre.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
