# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\WidgetApoyo\NoImageFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(501, 54)
        Form.setMaximumSize(QtCore.QSize(16777215, 60))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.background = QtWidgets.QWidget(Form)
        self.background.setStyleSheet("#background{\n"
"    background-color: #397bb8;\n"
"    border-radius: 20px;\n"
"}")
        self.background.setObjectName("background")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.background)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.background)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.punto = QtWidgets.QLabel(self.frame)
        self.punto.setMaximumSize(QtCore.QSize(30, 30))
        self.punto.setScaledContents(True)
        self.punto.setObjectName("punto")
        self.horizontalLayout.addWidget(self.punto)
        self.nombre = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nombre.setFont(font)
        self.nombre.setStyleSheet("#nombre{\n"
"    color: white;\n"
"}")
        self.nombre.setObjectName("nombre")
        self.horizontalLayout.addWidget(self.nombre)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.background)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.punto.setText(_translate("Form", "TextLabel"))
        self.nombre.setText(_translate("Form", "TextLabelfuyuyguyuvuvyvhgvugvgvuvuyvuyvuvuyvuvv"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
