# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\Empleados.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.background = QtWidgets.QWidget(Form)
        self.background.setStyleSheet("#background{\n"
"    background-color: purple;\n"
"}")
        self.background.setObjectName("background")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.background)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listado = QtWidgets.QWidget(self.background)
        self.listado.setStyleSheet("#listado{\n"
"    background-color: rgba(255, 255, 255, 210);\n"
"    border-radius: 14px;\n"
"    \n"
"}")
        self.listado.setObjectName("listado")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.listado)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.listado)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconoBuscar = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconoBuscar.sizePolicy().hasHeightForWidth())
        self.iconoBuscar.setSizePolicy(sizePolicy)
        self.iconoBuscar.setMaximumSize(QtCore.QSize(26, 26))
        self.iconoBuscar.setStyleSheet("#iconoBuscar{\n"
"    background-color: #185791;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    padding: 4px;\n"
"}")
        self.iconoBuscar.setScaledContents(True)
        self.iconoBuscar.setObjectName("iconoBuscar")
        self.horizontalLayout_2.addWidget(self.iconoBuscar)
        self.barraBusqueda = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.barraBusqueda.setFont(font)
        self.barraBusqueda.setStyleSheet("#barraBusqueda{\n"
"    background-color: #185791;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    color: white;\n"
"    padding: 4px;\n"
"}")
        self.barraBusqueda.setObjectName("barraBusqueda")
        self.horizontalLayout_2.addWidget(self.barraBusqueda)
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea = QtWidgets.QScrollArea(self.listado)
        self.scrollArea.setStyleSheet("#scrollArea{\n"
"    border: 0px solid black;\n"
"    border-radius: 14px;\n"
"}\n"
"#contenidoScroll{\n"
"    background-color: white;\n"
"    \n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.contenidoScroll = QtWidgets.QWidget()
        self.contenidoScroll.setGeometry(QtCore.QRect(0, 0, 222, 370))
        self.contenidoScroll.setObjectName("contenidoScroll")
        self.scrollArea.setWidget(self.contenidoScroll)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.listado)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.datos = QtWidgets.QWidget(self.background)
        self.datos.setStyleSheet("#widget{\n"
"    margin-left: 20px;\n"
"}")
        self.datos.setObjectName("datos")
        self.horizontalLayout.addWidget(self.datos)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 3)
        self.verticalLayout.addWidget(self.background)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.iconoBuscar.setText(_translate("Form", "aaaaa"))
        self.barraBusqueda.setPlaceholderText(_translate("Form", "Buscar Empleado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
