# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\MainMenuAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowMenuAdmin(object):
    def setupUi(self, MainWindowMenuAdmin):
        MainWindowMenuAdmin.setObjectName("MainWindowMenuAdmin")
        MainWindowMenuAdmin.resize(1068, 675)
        self.centralwidgetMenuAdmin = QtWidgets.QWidget(MainWindowMenuAdmin)
        self.centralwidgetMenuAdmin.setStyleSheet("#BotonMiniMenu, #BotonMiniMenu_2{\n"
"    background-color: #0363b7;\n"
"    border:  2px solid white;\n"
"    padding: 3px;\n"
"}")
        self.centralwidgetMenuAdmin.setObjectName("centralwidgetMenuAdmin")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidgetMenuAdmin)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BarraHerramientas = QtWidgets.QWidget(self.centralwidgetMenuAdmin)
        self.BarraHerramientas.setStyleSheet("#BarraHerramientas{\n"
"    background-color:  #0363b7;\n"
"}\n"
"\n"
"#BarraHerramientas QLabel{\n"
"    color: white;\n"
"}\n"
"\n"
"#BarraHerramientas QPushButton{\n"
"    color: white;\n"
"    background-color: #0363b7;\n"
"    border: none;\n"
"    padding: 9px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"#BarraHerramientas QPushButton:Hover{\n"
"     background-color: #015092;\n"
"}\n"
"\n"
"#FuncionesAdmin{\n"
"    background-color: #024f92;\n"
"    \n"
"}\n"
"\n"
"#FuncionesAdmin QPushButton{\n"
"    background-color: #024f92;\n"
"    padding-left: 20px;\n"
"}\n"
"\n"
"#FuncionesAdmin QPushButton:Hover{\n"
"    background-color: #024580;\n"
"}")
        self.BarraHerramientas.setObjectName("BarraHerramientas")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.BarraHerramientas)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topMinimenu = QtWidgets.QWidget(self.BarraHerramientas)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.topMinimenu.setFont(font)
        self.topMinimenu.setObjectName("topMinimenu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topMinimenu)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LabelEmpleado = QtWidgets.QLabel(self.topMinimenu)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LabelEmpleado.setFont(font)
        self.LabelEmpleado.setObjectName("LabelEmpleado")
        self.horizontalLayout_2.addWidget(self.LabelEmpleado)
        self.BotonMiniMenu_2 = QtWidgets.QPushButton(self.topMinimenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BotonMiniMenu_2.sizePolicy().hasHeightForWidth())
        self.BotonMiniMenu_2.setSizePolicy(sizePolicy)
        self.BotonMiniMenu_2.setMaximumSize(QtCore.QSize(50, 50))
        self.BotonMiniMenu_2.setStyleSheet("#BotonMiniMenu_2{\n"
"    background-color: #0363b7;\n"
"    border:  2px solid white;\n"
"    padding: 3px;\n"
"    text-align: center;\n"
"}")
        self.BotonMiniMenu_2.setObjectName("BotonMiniMenu_2")
        self.horizontalLayout_2.addWidget(self.BotonMiniMenu_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.topMinimenu, 0, QtCore.Qt.AlignTop)
        self.HomeButton = QtWidgets.QPushButton(self.BarraHerramientas)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.HomeButton.setFont(font)
        self.HomeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.HomeButton.setCheckable(False)
        self.HomeButton.setObjectName("HomeButton")
        self.verticalLayout_3.addWidget(self.HomeButton)
        self.ContenedorAdmin = QtWidgets.QWidget(self.BarraHerramientas)
        self.ContenedorAdmin.setObjectName("ContenedorAdmin")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ContenedorAdmin)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.HeaderFuncionesAdmin = QtWidgets.QWidget(self.ContenedorAdmin)
        self.HeaderFuncionesAdmin.setObjectName("HeaderFuncionesAdmin")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.HeaderFuncionesAdmin)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_imagen_admin = QtWidgets.QLabel(self.HeaderFuncionesAdmin)
        self.label_imagen_admin.setMaximumSize(QtCore.QSize(30, 30))
        self.label_imagen_admin.setScaledContents(True)
        self.label_imagen_admin.setWordWrap(True)
        self.label_imagen_admin.setObjectName("label_imagen_admin")
        self.horizontalLayout_3.addWidget(self.label_imagen_admin)
        self.AdminButton = QtWidgets.QPushButton(self.HeaderFuncionesAdmin)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.AdminButton.setFont(font)
        self.AdminButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AdminButton.setCheckable(False)
        self.AdminButton.setObjectName("AdminButton")
        self.horizontalLayout_3.addWidget(self.AdminButton)
        self.verticalLayout_5.addWidget(self.HeaderFuncionesAdmin)
        self.FuncionesAdmin = QtWidgets.QWidget(self.ContenedorAdmin)
        self.FuncionesAdmin.setStyleSheet("")
        self.FuncionesAdmin.setObjectName("FuncionesAdmin")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.FuncionesAdmin)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AdministrarProductos = QtWidgets.QPushButton(self.FuncionesAdmin)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.AdministrarProductos.setFont(font)
        self.AdministrarProductos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AdministrarProductos.setObjectName("AdministrarProductos")
        self.verticalLayout_4.addWidget(self.AdministrarProductos)
        self.AdministrarEmpleados = QtWidgets.QPushButton(self.FuncionesAdmin)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.AdministrarEmpleados.setFont(font)
        self.AdministrarEmpleados.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AdministrarEmpleados.setObjectName("AdministrarEmpleados")
        self.verticalLayout_4.addWidget(self.AdministrarEmpleados)
        self.AdministrarPromociones = QtWidgets.QPushButton(self.FuncionesAdmin)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.AdministrarPromociones.setFont(font)
        self.AdministrarPromociones.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AdministrarPromociones.setObjectName("AdministrarPromociones")
        self.verticalLayout_4.addWidget(self.AdministrarPromociones)
        self.AdministrarVentas = QtWidgets.QPushButton(self.FuncionesAdmin)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.AdministrarVentas.setFont(font)
        self.AdministrarVentas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AdministrarVentas.setObjectName("AdministrarVentas")
        self.verticalLayout_4.addWidget(self.AdministrarVentas)
        self.AdministrarGastos = QtWidgets.QPushButton(self.FuncionesAdmin)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.AdministrarGastos.setFont(font)
        self.AdministrarGastos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AdministrarGastos.setObjectName("AdministrarGastos")
        self.verticalLayout_4.addWidget(self.AdministrarGastos)
        self.Estadisticas = QtWidgets.QPushButton(self.FuncionesAdmin)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.Estadisticas.setFont(font)
        self.Estadisticas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Estadisticas.setObjectName("Estadisticas")
        self.verticalLayout_4.addWidget(self.Estadisticas)
        self.InventarioButton = QtWidgets.QPushButton(self.FuncionesAdmin)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.InventarioButton.setFont(font)
        self.InventarioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.InventarioButton.setObjectName("InventarioButton")
        self.verticalLayout_4.addWidget(self.InventarioButton)
        self.verticalLayout_5.addWidget(self.FuncionesAdmin)
        self.verticalLayout_3.addWidget(self.ContenedorAdmin)
        self.Vender = QtWidgets.QPushButton(self.BarraHerramientas)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Vender.setFont(font)
        self.Vender.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Vender.setCheckable(False)
        self.Vender.setObjectName("Vender")
        self.verticalLayout_3.addWidget(self.Vender)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.BarraHerramientas)
        self.BarraDeHerramientoMini = QtWidgets.QWidget(self.centralwidgetMenuAdmin)
        self.BarraDeHerramientoMini.setStyleSheet("#BarraDeHerramientoMini{\n"
"    background-color: #0363b7;\n"
"}")
        self.BarraDeHerramientoMini.setObjectName("BarraDeHerramientoMini")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.BarraDeHerramientoMini)
        self.verticalLayout_2.setContentsMargins(-1, 18, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BotonMiniMenu = QtWidgets.QPushButton(self.BarraDeHerramientoMini)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BotonMiniMenu.sizePolicy().hasHeightForWidth())
        self.BotonMiniMenu.setSizePolicy(sizePolicy)
        self.BotonMiniMenu.setMaximumSize(QtCore.QSize(50, 50))
        self.BotonMiniMenu.setStyleSheet("")
        self.BotonMiniMenu.setObjectName("BotonMiniMenu")
        self.verticalLayout_2.addWidget(self.BotonMiniMenu, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.BarraDeHerramientoMini)
        self.Stacked = QtWidgets.QWidget(self.centralwidgetMenuAdmin)
        self.Stacked.setObjectName("Stacked")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Stacked)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Stacked)
        self.stackedWidget.setObjectName("stackedWidget")
        self.MenuGrande = QtWidgets.QWidget()
        self.MenuGrande.setObjectName("MenuGrande")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.MenuGrande)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.MenuGrandeImagen = QtWidgets.QLabel(self.MenuGrande)
        self.MenuGrandeImagen.setMaximumSize(QtCore.QSize(400, 400))
        self.MenuGrandeImagen.setScaledContents(True)
        self.MenuGrandeImagen.setWordWrap(False)
        self.MenuGrandeImagen.setObjectName("MenuGrandeImagen")
        self.verticalLayout_6.addWidget(self.MenuGrandeImagen, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.MenuGrande)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.Stacked)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(2, 9)
        MainWindowMenuAdmin.setCentralWidget(self.centralwidgetMenuAdmin)

        self.retranslateUi(MainWindowMenuAdmin)
        QtCore.QMetaObject.connectSlotsByName(MainWindowMenuAdmin)

    def retranslateUi(self, MainWindowMenuAdmin):
        _translate = QtCore.QCoreApplication.translate
        MainWindowMenuAdmin.setWindowTitle(_translate("MainWindowMenuAdmin", "MainWindow"))
        self.LabelEmpleado.setText(_translate("MainWindowMenuAdmin", "TextLabel"))
        self.BotonMiniMenu_2.setText(_translate("MainWindowMenuAdmin", "PushButton"))
        self.HomeButton.setText(_translate("MainWindowMenuAdmin", "Inicio"))
        self.label_imagen_admin.setText(_translate("MainWindowMenuAdmin", "TextLabel"))
        self.AdminButton.setText(_translate("MainWindowMenuAdmin", "Funciones de Administrador"))
        self.AdministrarProductos.setText(_translate("MainWindowMenuAdmin", "Administrar Productos"))
        self.AdministrarEmpleados.setText(_translate("MainWindowMenuAdmin", "Administrar Empleados"))
        self.AdministrarPromociones.setText(_translate("MainWindowMenuAdmin", "Administrar Promociones"))
        self.AdministrarVentas.setText(_translate("MainWindowMenuAdmin", "Administrar Ventas"))
        self.AdministrarGastos.setText(_translate("MainWindowMenuAdmin", "Administrar Gastos"))
        self.Estadisticas.setText(_translate("MainWindowMenuAdmin", "Estadísticas"))
        self.InventarioButton.setText(_translate("MainWindowMenuAdmin", "Inventario"))
        self.Vender.setText(_translate("MainWindowMenuAdmin", "Vender Productos"))
        self.BotonMiniMenu.setText(_translate("MainWindowMenuAdmin", "PushButton"))
        self.MenuGrandeImagen.setText(_translate("MainWindowMenuAdmin", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowMenuAdmin = QtWidgets.QMainWindow()
    ui = Ui_MainWindowMenuAdmin()
    ui.setupUi(MainWindowMenuAdmin)
    MainWindowMenuAdmin.show()
    sys.exit(app.exec_())
