# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\Pagar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(817, 616)
        Form.setWindowOpacity(1.0)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_atras_pago = QtWidgets.QWidget(Form)
        self.widget_atras_pago.setStyleSheet("#widget_atras_pago{\n"
"    background-color: #010c54;;\n"
"}")
        self.widget_atras_pago.setObjectName("widget_atras_pago")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_atras_pago)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetParaTabla = QtWidgets.QWidget(self.widget_atras_pago)
        self.widgetParaTabla.setObjectName("widgetParaTabla")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widgetParaTabla)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.WidgetVentaTabla = QtWidgets.QWidget(self.widgetParaTabla)
        self.WidgetVentaTabla.setStyleSheet("#WidgetVentaTabla {\n"
"    background-color: #185791;\n"
"    border-radius: 12px;\n"
"}")
        self.WidgetVentaTabla.setObjectName("WidgetVentaTabla")
        self.LayoutVenta = QtWidgets.QVBoxLayout(self.WidgetVentaTabla)
        self.LayoutVenta.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.LayoutVenta.setContentsMargins(20, 20, 20, 20)
        self.LayoutVenta.setSpacing(20)
        self.LayoutVenta.setObjectName("LayoutVenta")
        self.WidgetInteriorVentaTabla = QtWidgets.QWidget(self.WidgetVentaTabla)
        self.WidgetInteriorVentaTabla.setStyleSheet("#WidgetInteriorVentaTabla{\n"
"    border: 3px solid white;\n"
"}")
        self.WidgetInteriorVentaTabla.setObjectName("WidgetInteriorVentaTabla")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.WidgetInteriorVentaTabla)
        self.verticalLayout_2.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Venta = QtWidgets.QLabel(self.WidgetInteriorVentaTabla)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Venta.setFont(font)
        self.Venta.setStyleSheet("#Venta{\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}")
        self.Venta.setScaledContents(False)
        self.Venta.setAlignment(QtCore.Qt.AlignCenter)
        self.Venta.setObjectName("Venta")
        self.verticalLayout_2.addWidget(self.Venta)
        self.TablaVenta = QtWidgets.QTableWidget(self.WidgetInteriorVentaTabla)
        self.TablaVenta.setStyleSheet("QHeaderView::section {\n"
"    background-color: #f1473a;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: 1px solid white;\n"
"}")
        self.TablaVenta.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.TablaVenta.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TablaVenta.setLineWidth(1)
        self.TablaVenta.setMidLineWidth(1)
        self.TablaVenta.setColumnCount(5)
        self.TablaVenta.setObjectName("TablaVenta")
        self.TablaVenta.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablaVenta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaVenta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaVenta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaVenta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaVenta.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.TablaVenta)
        self.widgetTotal = QtWidgets.QWidget(self.WidgetInteriorVentaTabla)
        self.widgetTotal.setStyleSheet("#widgetTotal QLabel{\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}")
        self.widgetTotal.setObjectName("widgetTotal")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetTotal)
        self.horizontalLayout_2.setContentsMargins(0, 11, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPrecioTotal = QtWidgets.QLabel(self.widgetTotal)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelPrecioTotal.setFont(font)
        self.labelPrecioTotal.setObjectName("labelPrecioTotal")
        self.horizontalLayout_2.addWidget(self.labelPrecioTotal)
        self.LabelPrecioTotalDecimal = QtWidgets.QLabel(self.widgetTotal)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LabelPrecioTotalDecimal.setFont(font)
        self.LabelPrecioTotalDecimal.setObjectName("LabelPrecioTotalDecimal")
        self.horizontalLayout_2.addWidget(self.LabelPrecioTotalDecimal, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.widgetTotal)
        self.LayoutVenta.addWidget(self.WidgetInteriorVentaTabla)
        self.verticalLayout_7.addWidget(self.WidgetVentaTabla)
        self.horizontalLayout.addWidget(self.widgetParaTabla)
        self.widgetPago = QtWidgets.QWidget(self.widget_atras_pago)
        self.widgetPago.setStyleSheet("#widgetPago{\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#widgetPago QLineEdit{\n"
"    background-color: #e7e7e5;\n"
"    border: none;\n"
"    border-bottom: 2px solid black ;\n"
"}")
        self.widgetPago.setObjectName("widgetPago")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetPago)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelEfectivo = QtWidgets.QLabel(self.widgetPago)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelEfectivo.setFont(font)
        self.labelEfectivo.setObjectName("labelEfectivo")
        self.verticalLayout_3.addWidget(self.labelEfectivo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frameTotal = QtWidgets.QWidget(self.widgetPago)
        self.frameTotal.setObjectName("frameTotal")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameTotal)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelTotal = QtWidgets.QLabel(self.frameTotal)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelTotal.setFont(font)
        self.labelTotal.setObjectName("labelTotal")
        self.verticalLayout_5.addWidget(self.labelTotal)
        self.lineEditPagado_2 = QtWidgets.QLineEdit(self.frameTotal)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditPagado_2.setFont(font)
        self.lineEditPagado_2.setObjectName("lineEditPagado_2")
        self.verticalLayout_5.addWidget(self.lineEditPagado_2)
        self.verticalLayout_3.addWidget(self.frameTotal, 0, QtCore.Qt.AlignTop)
        self.framePagado = QtWidgets.QWidget(self.widgetPago)
        self.framePagado.setObjectName("framePagado")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.framePagado)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelPagado = QtWidgets.QLabel(self.framePagado)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelPagado.setFont(font)
        self.labelPagado.setObjectName("labelPagado")
        self.verticalLayout_4.addWidget(self.labelPagado)
        self.lineEditPagado = QtWidgets.QLineEdit(self.framePagado)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditPagado.setFont(font)
        self.lineEditPagado.setObjectName("lineEditPagado")
        self.verticalLayout_4.addWidget(self.lineEditPagado)
        self.verticalLayout_3.addWidget(self.framePagado, 0, QtCore.Qt.AlignVCenter)
        self.FrameCambio = QtWidgets.QWidget(self.widgetPago)
        self.FrameCambio.setObjectName("FrameCambio")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.FrameCambio)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelCambio = QtWidgets.QLabel(self.FrameCambio)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelCambio.setFont(font)
        self.labelCambio.setObjectName("labelCambio")
        self.verticalLayout_6.addWidget(self.labelCambio)
        self.lineEditCambio = QtWidgets.QLineEdit(self.FrameCambio)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditCambio.setFont(font)
        self.lineEditCambio.setObjectName("lineEditCambio")
        self.verticalLayout_6.addWidget(self.lineEditCambio)
        self.verticalLayout_3.addWidget(self.FrameCambio, 0, QtCore.Qt.AlignTop)
        self.buttonFinalizarCompra = QtWidgets.QPushButton(self.widgetPago)
        self.buttonFinalizarCompra.setStyleSheet("#buttonFinalizarCompra{\n"
"    color: white;\n"
"    background-color: #f1473a;\n"
"    border: none;\n"
"    padding: 6px 24px;\n"
"    border-radius: 8px;    \n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#buttonFinalizarCompra:Hover{\n"
"    background-color: #C73A30;\n"
"}")
        self.buttonFinalizarCompra.setObjectName("buttonFinalizarCompra")
        self.verticalLayout_3.addWidget(self.buttonFinalizarCompra, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.setStretch(0, 18)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 7)
        self.verticalLayout_3.setStretch(3, 100)
        self.horizontalLayout.addWidget(self.widgetPago)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addWidget(self.widget_atras_pago)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Venta.setText(_translate("Form", "Venta"))
        item = self.TablaVenta.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Producto"))
        item = self.TablaVenta.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Cantidad"))
        item = self.TablaVenta.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Precio"))
        item = self.TablaVenta.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Subtotal"))
        item = self.TablaVenta.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Id_producto"))
        self.labelPrecioTotal.setText(_translate("Form", "Total"))
        self.LabelPrecioTotalDecimal.setText(_translate("Form", "$0"))
        self.labelEfectivo.setText(_translate("Form", "Efectivo"))
        self.labelTotal.setText(_translate("Form", "Total:"))
        self.labelPagado.setText(_translate("Form", "Pagado:"))
        self.labelCambio.setText(_translate("Form", "Cambio:"))
        self.buttonFinalizarCompra.setText(_translate("Form", "Pagar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
