# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\Venta.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 621)
        self.WidgetVentaTotal = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidgetVentaTotal.sizePolicy().hasHeightForWidth())
        self.WidgetVentaTotal.setSizePolicy(sizePolicy)
        self.WidgetVentaTotal.setObjectName("WidgetVentaTotal")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.WidgetVentaTotal)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollAreaProducto = QtWidgets.QScrollArea(self.WidgetVentaTotal)
        self.scrollAreaProducto.setStyleSheet("#scrollAreaProducto {\n"
"background-color: rgba(255,255,255,0.5);\n"
"}")
        self.scrollAreaProducto.setWidgetResizable(True)
        self.scrollAreaProducto.setObjectName("scrollAreaProducto")
        self.scrollAreaContentsProductos = QtWidgets.QWidget()
        self.scrollAreaContentsProductos.setGeometry(QtCore.QRect(0, 0, 524, 550))
        self.scrollAreaContentsProductos.setObjectName("scrollAreaContentsProductos")
        self.scrollAreaProducto.setWidget(self.scrollAreaContentsProductos)
        self.horizontalLayout_2.addWidget(self.scrollAreaProducto)
        self.WidgetVentaTabla = QtWidgets.QWidget(self.WidgetVentaTotal)
        self.WidgetVentaTabla.setStyleSheet("#WidgetVentaTabla {\n"
"background-color: rgba(255,255,255,0.5)\n"
"}")
        self.WidgetVentaTabla.setObjectName("WidgetVentaTabla")
        self.LayoutVenta = QtWidgets.QVBoxLayout(self.WidgetVentaTabla)
        self.LayoutVenta.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.LayoutVenta.setContentsMargins(10, 10, 10, 10)
        self.LayoutVenta.setSpacing(20)
        self.LayoutVenta.setObjectName("LayoutVenta")
        self.Venta = QtWidgets.QLabel(self.WidgetVentaTabla)
        self.Venta.setScaledContents(False)
        self.Venta.setAlignment(QtCore.Qt.AlignCenter)
        self.Venta.setObjectName("Venta")
        self.LayoutVenta.addWidget(self.Venta)
        self.TablaVenta = QtWidgets.QTableWidget(self.WidgetVentaTabla)
        self.TablaVenta.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.TablaVenta.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TablaVenta.setLineWidth(1)
        self.TablaVenta.setMidLineWidth(1)
        self.TablaVenta.setObjectName("TablaVenta")
        self.TablaVenta.setColumnCount(5)
        self.TablaVenta.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablaVenta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaVenta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaVenta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaVenta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaVenta.setHorizontalHeaderItem(4, item)
        self.LayoutVenta.addWidget(self.TablaVenta)
        self.horizontalLayout_2.addWidget(self.WidgetVentaTabla)
        MainWindow.setCentralWidget(self.WidgetVentaTotal)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Venta.setText(_translate("MainWindow", "Venta"))
        item = self.TablaVenta.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Producto"))
        item = self.TablaVenta.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.TablaVenta.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Precio"))
        item = self.TablaVenta.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Subtotal"))
        item = self.TablaVenta.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
