# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RawInterfaces\Venta.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollAreaProducto = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaProducto.setWidgetResizable(True)
        self.scrollAreaProducto.setObjectName("scrollAreaProducto")
        self.scrollAreaContentsProductos = QtWidgets.QWidget()
        self.scrollAreaContentsProductos.setGeometry(QtCore.QRect(0, 0, 463, 549))
        self.scrollAreaContentsProductos.setObjectName("scrollAreaContentsProductos")
        self.scrollAreaProducto.setWidget(self.scrollAreaContentsProductos)
        self.horizontalLayout_2.addWidget(self.scrollAreaProducto)
        self.LayoutVenta = QtWidgets.QVBoxLayout()
        self.LayoutVenta.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.LayoutVenta.setContentsMargins(10, 10, 10, 10)
        self.LayoutVenta.setSpacing(20)
        self.LayoutVenta.setObjectName("LayoutVenta")
        self.Venta = QtWidgets.QLabel(self.centralwidget)
        self.Venta.setScaledContents(False)
        self.Venta.setAlignment(QtCore.Qt.AlignCenter)
        self.Venta.setObjectName("Venta")
        self.LayoutVenta.addWidget(self.Venta)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setMidLineWidth(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.LayoutVenta.addWidget(self.tableWidget)
        self.horizontalLayout_2.addLayout(self.LayoutVenta)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Venta.setText(_translate("MainWindow", "Venta"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Producto"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Subtotal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
